- lib/htmlWriter.js
- lib/parser.js
- lib/util.js
- test/test_parser.js
> Added bugfix for #4

- lib/jsonquery.js
- test/FromModelica/CustomPWithLimiter-simplified.json
- test/FromModelica/CustomPWithLimiter.html
- test/FromModelica/CustomPWithLimiter.json
- test/FromModelica/CustomPWithLimiter.mo
- test/FromModelica/package.order
> Added test case

- lib/htmlWriter.js
- lib/jsonquery.js
- lib/page.html
- test/FromModelica/Block1.html
- test/FromModelica/BlockInputOutput.html
- test/FromModelica/BlockWithBlock1.html
- test/FromModelica/CustomPWithLimiter-simplified.json
- test/FromModelica/CustomPWithLimiter.html
- test/FromModelica/CustomPWithLimiter.json
- test/FromModelica/CustomPWithLimiter.mo
- test/FromModelica/Parameter1.html
- test/FromModelica/Parameter1WithVendorAnnotation.html
- test/FromModelica/Parameter2.html
- test/FromModelica/ParameterWithInfo.html
- test/FromModelica/package.html
- test/test_util.js
> Issue9 links

- lib/jsonquery.js
- test/FromModelica/BlockInputOutput-simplified.json
- test/FromModelica/BlockWithBlock1-simplified.json
- test/FromModelica/CustomPWithLimiter-simplified.json
- test/FromModelica/Parameter1-simplified.json
- test/FromModelica/Parameter1WithVendorAnnotation-simplified.json
- test/FromModelica/Parameter2-simplified.json
- test/FromModelica/ParameterWithInfo-simplified.json
- test/FromModelica/package-simplified.json
> Issue14 annotation parameter

- Makefile
- app.js
> Issue16 argument

- java/parser/src/main/java/gov/lbl/parser/domain/Composition.java
> updated parser to handle ibpsa vendor annotation #18

- Makefile
- lib/htmlWriter.js
- lib/jsonquery.js
- test/FromModelica/Block1.html
- test/FromModelica/BlockInputOutput-simplified.json
- test/FromModelica/BlockInputOutput.html
- test/FromModelica/BlockWithBlock1-simplified.json
- test/FromModelica/BlockWithBlock1.html
- test/FromModelica/CustomPWithLimiter-simplified.json
- test/FromModelica/CustomPWithLimiter.html
- test/FromModelica/Parameter1-simplified.json
- test/FromModelica/Parameter1.html
- test/FromModelica/Parameter1WithVendorAnnotation-simplified.json
- test/FromModelica/Parameter1WithVendorAnnotation.html
- test/FromModelica/Parameter2-simplified.json
- test/FromModelica/Parameter2.html
- test/FromModelica/ParameterWithInfo-simplified.json
- test/FromModelica/ParameterWithInfo.html
- test/FromModelica/package-simplified.json
- test/FromModelica/package.html
- test/test_parser.js
> Issue19 html elements

- java/parser/src/main/java/gov/lbl/parser/domain/Comment.java
- java/parser/src/main/java/gov/lbl/parser/domain/Composition.java
- java/parser/src/main/java/gov/lbl/parser/domain/Connect_clause.java
- test/FromModelica/CustomPWithLimiter-simplified.json
- test/FromModelica/CustomPWithLimiter.html
- test/FromModelica/CustomPWithLimiter.json
> correct connection parsing #22

- Makefile
- lib/htmlWriter.js
- lib/jsonquery.js
- test/FromModelica/Block1-simplified.json
- test/FromModelica/BlockInputOutput-simplified.json
- test/FromModelica/BlockInputOutput.html
- test/FromModelica/BlockWithBlock1-simplified.json
- test/FromModelica/BlockWithBlock1.html
- test/FromModelica/CustomPWithLimiter-simplified.json
- test/FromModelica/CustomPWithLimiter.html
- test/FromModelica/Parameter1-simplified.json
- test/FromModelica/Parameter1.html
- test/FromModelica/Parameter1WithVendorAnnotation-simplified.json
- test/FromModelica/Parameter1WithVendorAnnotation.html
- test/FromModelica/Parameter2-simplified.json
- test/FromModelica/Parameter2.html
- test/FromModelica/ParameterWithInfo-simplified.json
- test/FromModelica/ParameterWithInfo.html
- test/FromModelica/package-simplified.json
- test/FromModelica/package.html
- test/test_parser.js
> Issue25 par grouping

- java/parser/src/main/java/gov/lbl/parser/domain/Comment.java
> fixed parsing error #27

- lib/htmlWriter.js
> Added bugfix for #29

- lib/htmlWriter.js
- lib/jsonquery.js
- lib/parser.js
- test/FromModelica/BlockInputOutput-simplified.json
- test/FromModelica/BlockWithBlock1-simplified.json
- test/FromModelica/CustomPWithLimiter-simplified.json
- test/FromModelica/Parameter1-simplified.json
- test/FromModelica/Parameter1WithVendorAnnotation-simplified.json
- test/FromModelica/Parameter2-simplified.json
- test/FromModelica/ParameterWithInfo-simplified.json
- test/FromModelica/package-simplified.json
> Removed within in the instance declaration for #37

- Makefile
> updated Maven download link #39

- Makefile
- README.md
> Updated maven and readme file

- lib/jsonquery.js
> Commented test to make parser work for models

- Makefile
- app.js
- lib/htmlWriter.js
- lib/jsonquery.js
- lib/modelicaToJSON.js
- lib/parser.js
- lib/util.js
- test/FromModelica/cdl/simplified/FromModelica.BlockInputOutput.json
- test/FromModelica/cdl/simplified/FromModelica.CustomPWithLimiter.json
- test/FromModelica/cdl/simplified/FromModelica.Modulation.json
> Changed to relative file path

- lib/modelicaToJSON.js
- lib/parser.js
- lib/util.js
> Issue64 improve err msg

- schema-CDL.json
- schema-modelica.json
Updated : 
- required statement for CoordinateSystem
- type of data in the "public" section.
> Updated data types for both Schemas (for #85)

- lib/jsonquery.js
Added Modelica SI Units for Angle and Frequency in jsonquery.js. 
Units definitions from [Modelica online manual](https://www.maplesoft.com/documentation_center/online_manuals/modelica/Modelica_SIunits.html) 
Successfully tested the parsing of Buildings/Controls/OBC/CDL/Continuous/Sine.mo
> Issue87 si units

- README.md
Changed the Readme file to redirect to the detailed documentation file.
> Updated link to website for #73

- lib/util.js
> avoided creating html file when there is package.mo file, #60

- Makefile
- java/pom.xml
> updated maven link, updated plugin version

- schema-modelica.json
> updated modelica schema

- Makefile
- app.js
- lib/jsonquery.js
- lib/util.js
> Issue128 abs schema path

- app.js
> added strict flag

- app.js
- lib/htmlWriter.js
- lib/jsonquery.js
- lib/parser.js
- lib/util.js
> updated the check of warning message, #130

- lib/svgDiagram.js
> removed dots

- Makefile
- app.js
- lib/parser.js
- lib/util.js
- test/FromModelica/cdl/svg/FromModelica.Block1.svg
- test/FromModelica/cdl/svg/FromModelica.BlockInputOutput.svg
- test/FromModelica/cdl/svg/FromModelica.BlockWithBlock1.svg
- test/FromModelica/cdl/svg/FromModelica.ConditionalBlock.svg
- test/FromModelica/cdl/svg/FromModelica.CustomPWithLimiter.svg
- test/FromModelica/cdl/svg/FromModelica.DynamicTextColor.svg
- test/FromModelica/cdl/svg/FromModelica.EmptyEquation.svg
- test/FromModelica/cdl/svg/FromModelica.MisplacedInfoWithComponent.svg
- test/FromModelica/cdl/svg/FromModelica.MisplacedInfoWithEquation.svg
- test/FromModelica/cdl/svg/FromModelica.MisplacedInfoWithParameter.svg
- test/FromModelica/cdl/svg/FromModelica.Modulation.svg
- test/FromModelica/cdl/svg/FromModelica.NoClassComment.svg
- test/FromModelica/cdl/svg/FromModelica.NoWithin-package.svg
- test/FromModelica/cdl/svg/FromModelica.Parameter1.svg
- test/FromModelica/cdl/svg/FromModelica.Parameter1WithVendorAnnotation.svg
- test/FromModelica/cdl/svg/FromModelica.Parameter2.svg
- test/FromModelica/cdl/svg/FromModelica.Parameter3.svg
- test/FromModelica/cdl/svg/FromModelica.ParameterWithDefaultName.svg
- test/FromModelica/cdl/svg/FromModelica.ParameterWithInfo.svg
- test/FromModelica/cdl/svg/FromModelica.ParameterWithVendorAnnotationInInfo.svg
- test/FromModelica/cdl/svg/FromModelica.RemovableInputs.svg
- test/FromModelica/cdl/svg/FromModelica.VariableModification.svg
- test/FromModelica/cdl/svg/FromModelica.WithCDLElementary.svg
- test/FromModelica/cdl/svg/FromModelica.package.svg
> Enabled svg output option in cdl mode

- java/pom.xml
> upgraded guava version

- Makefile
> updated the maven link to the acheved linke

- lib/graphicalPrimitives.js
- lib/jsonquery.js
- package.json
- test/test_graphicalPrimitive.js
- test/test_jsonquery.js
updating unit tests for modelica-json to increase code coverage.
> Issue198 unittests

- lib/cxfExtractor.js
- lib/objectExtractor.js
- lib/parser.js
> Issue242 check parsed classes

- lib/modelicaToJSON.js
- lib/util.js
> Fix and rename relativePath()

- lib/cxfExtractor.js
- lib/parser.js
> Refactor for Boolean prettyPrint

- lib/cdlDoc.js
- test/test_cdlDoc.js
> Refactor CDL visibility toggling with template element

- lib/expressionEvaluation.js
> Fix class name lookup for single file mapping
